//! Factory sounds and the shared preset-system seam.

use std::sync::RwLock;

pub use mxm_preset::{
    Category, Entry, INIT_NAME, Library, Loaded, Origin, Preset, PresetIdentity, Refused, Value,
    factory, loaded, mark_loaded, mark_none, read_favourites, snapshot, write_favourites,
};

use crate::params::MxmFxDelayParams;

/// **The tempo syncs this plugin gained on 2026-09-25** (`plans/plan-tempo-sync-controls.md`). A
/// preset file written before them was written unsynced, so each loads off rather than keeping the
/// instance's sync, and without reporting a missing control.
pub(crate) const TEMPO_SYNC_IDS: &[&str] = &["ratesync"];

impl mxm_preset::Instrument for MxmFxDelayParams {
    fn clap_id(&self) -> &'static str {
        crate::CLAP_ID
    }

    fn parameters(&self) -> Vec<(&'static str, &dyn mxm_preset::ErasedParam)> {
        vec![
            ("time", &self.time),
            ("sync", &self.sync),
            ("change", &self.change),
            ("routing", &self.routing),
            ("offset", &self.offset),
            ("feedback", &self.feedback),
            ("lowcut", &self.low_cut),
            ("highcut", &self.high_cut),
            ("drive", &self.drive),
            ("freeze", &self.freeze),
            ("model", &self.model),
            ("character", &self.character),
            ("motion", &self.motion),
            ("rate", &self.rate),
            ("ratesync", &self.rate_sync),
            ("shape", &self.shape),
            ("duck", &self.duck),
            ("mix", &self.mix),
        ]
    }

    fn identity(&self) -> &RwLock<PresetIdentity> {
        &self.preset
    }

    fn factory_files(&self) -> &'static [(&'static str, &'static str)] {
        FACTORY_FILES
    }

    fn default_missing_legacy_parameter(&self, id: &str) -> bool {
        TEMPO_SYNC_IDS.contains(&id)
    }

    fn is_factory_preserved(&self, id: &str) -> bool {
        id == "mix"
    }
}

// Generated by `examples/fx_delay_build_presets.rs` from `preset_designs.rs`.
pub const FACTORY_FILES: &[(&str, &str)] = &[
    (
        "bright-memory",
        include_str!("../presets/bright-memory.json"),
    ),
    (
        "bright-runaway",
        include_str!("../presets/bright-runaway.json"),
    ),
    ("clean-chorus", include_str!("../presets/clean-chorus.json")),
    ("clean-eighth", include_str!("../presets/clean-eighth.json")),
    (
        "clean-quarter",
        include_str!("../presets/clean-quarter.json"),
    ),
    (
        "clock-descent",
        include_str!("../presets/clock-descent.json"),
    ),
    (
        "clocked-vocal",
        include_str!("../presets/clocked-vocal.json"),
    ),
    ("dark-throw", include_str!("../presets/dark-throw.json")),
    (
        "digital-dotted",
        include_str!("../presets/digital-dotted.json"),
    ),
    (
        "digital-orbit",
        include_str!("../presets/digital-orbit.json"),
    ),
    ("digital-ping", include_str!("../presets/digital-ping.json")),
    ("dotted-lift", include_str!("../presets/dotted-lift.json")),
    ("dub-clean", include_str!("../presets/dub-clean.json")),
    ("dub-digital", include_str!("../presets/dub-digital.json")),
    ("dub-tape", include_str!("../presets/dub-tape.json")),
    ("ducked-dub", include_str!("../presets/ducked-dub.json")),
    (
        "edge-of-orbit",
        include_str!("../presets/edge-of-orbit.json"),
    ),
    (
        "fast-shimmer-echo",
        include_str!("../presets/fast-shimmer-echo.json"),
    ),
    ("grainy-width", include_str!("../presets/grainy-width.json")),
    ("guitar-room", include_str!("../presets/guitar-room.json")),
    ("left-first", include_str!("../presets/left-first.json")),
    ("long-clear", include_str!("../presets/long-clear.json")),
    (
        "long-converter",
        include_str!("../presets/long-converter.json"),
    ),
    (
        "maintained-tape",
        include_str!("../presets/maintained-tape.json"),
    ),
    ("moving-ping", include_str!("../presets/moving-ping.json")),
    (
        "narrow-memory",
        include_str!("../presets/narrow-memory.json"),
    ),
    ("ping-horizon", include_str!("../presets/ping-horizon.json")),
    ("ping-rhythm", include_str!("../presets/ping-rhythm.json")),
    ("plain-echo", include_str!("../presets/plain-echo.json")),
    (
        "random-memory",
        include_str!("../presets/random-memory.json"),
    ),
    ("random-width", include_str!("../presets/random-width.json")),
    ("right-first", include_str!("../presets/right-first.json")),
    ("self-field", include_str!("../presets/self-field.json")),
    ("short-slap", include_str!("../presets/short-slap.json")),
    ("slow-horizon", include_str!("../presets/slow-horizon.json")),
    (
        "slow-transport",
        include_str!("../presets/slow-transport.json"),
    ),
    (
        "stereo-quarter",
        include_str!("../presets/stereo-quarter.json"),
    ),
    ("tape-dotted", include_str!("../presets/tape-dotted.json")),
    ("tape-drift", include_str!("../presets/tape-drift.json")),
    ("tape-flutter", include_str!("../presets/tape-flutter.json")),
    ("tape-pair", include_str!("../presets/tape-pair.json")),
    (
        "tape-stop-play",
        include_str!("../presets/tape-stop-play.json"),
    ),
    (
        "travelling-ping",
        include_str!("../presets/travelling-ping.json"),
    ),
    (
        "triangle-double",
        include_str!("../presets/triangle-double.json"),
    ),
    ("twin-slap", include_str!("../presets/twin-slap.json")),
    ("voice-pocket", include_str!("../presets/voice-pocket.json")),
    ("warm-echo", include_str!("../presets/warm-echo.json")),
    ("wide-pair", include_str!("../presets/wide-pair.json")),
    (
        "wide-reverse-lead",
        include_str!("../presets/wide-reverse-lead.json"),
    ),
    ("worn-repeat", include_str!("../presets/worn-repeat.json")),
];

#[cfg(test)]
mod tests {
    use super::*;

    /// **A project saved before the tempo syncs restores them Off** (`mxm_preset::add_switches_off`),
    /// whatever this instance had.
    #[test]
    fn an_older_state_restores_the_tempo_syncs_off() {
        use nice_plug::prelude::Plugin as _;
        let mut state = nice_plug::prelude::PluginState {
            version: String::new(),
            params: Default::default(),
            fields: Default::default(),
        };
        crate::MxmFxDelay::filter_state(&mut state);
        for id in TEMPO_SYNC_IDS {
            assert!(
                matches!(
                    state.params.get(*id),
                    Some(nice_plug::plugin::ParamValue::Bool(false))
                ),
                "{{id}} was not restored off"
            );
        }
    }

    /// **A preset saved before the tempo syncs loads them off, and cleanly** ([`TEMPO_SYNC_IDS`]).
    #[test]
    fn a_preset_from_before_the_tempo_syncs_loads_them_off() {
        let params = crate::params::MxmFxDelayParams::default();
        let mut old = mxm_preset::Preset::init(&params);
        for id in TEMPO_SYNC_IDS {
            old.params.remove(*id);
        }
        let (writes, problems) = old.resolve(&params);
        assert!(problems.is_empty(), "{{problems:?}}");
        for id in TEMPO_SYNC_IDS {
            assert!(
                writes.iter().any(|(w, _, v)| w == id && *v == 0.0),
                "{{id}} was not written off"
            );
        }
    }

    use mxm_preset::Instrument;

    #[test]
    fn every_parameter_is_declared_once_and_mix_is_the_only_factory_preserved_one() {
        let params = MxmFxDelayParams::default();
        let declared = params.parameters();
        assert_eq!(declared.len(), 18);
        for (index, (id, _)) in declared.iter().enumerate() {
            assert_eq!(
                declared.iter().filter(|(other, _)| other == id).count(),
                1,
                "{index}: {id}"
            );
            assert_eq!(params.is_factory_preserved(id), *id == "mix");
        }
    }

    #[test]
    fn init_is_complete_but_a_trusted_factory_recipe_may_omit_only_mix() {
        let params = MxmFxDelayParams::default();
        let init = Preset::init(&params);
        assert_eq!(init.params.len(), 18);
        let mut recipe = Preset::capture("Recipe", Category::Fx, &params);
        recipe.params.remove("mix");
        let (writes, problems) = recipe.resolve_from(&params, Some(&Origin::Factory));
        assert!(problems.is_empty(), "{problems:?}");
        assert_eq!(writes.len(), 17);
        let (_, direct_problems) = recipe.resolve(&params);
        assert_eq!(direct_problems.len(), 1);
        assert!(direct_problems[0].contains("mix"));
        let (_, user_problems) = recipe.resolve_from(&params, Some(&Origin::User));
        assert_eq!(user_problems.len(), 1);
    }

    #[test]
    fn control_map_names_only_live_parameters_and_the_intended_roles() {
        let params = MxmFxDelayParams::default();
        let live: std::collections::BTreeSet<_> =
            params.parameters().into_iter().map(|(id, _)| id).collect();
        let map: serde_json::Value =
            serde_json::from_str(include_str!("../control-map.json")).unwrap();
        let mappings = map["instruments"][0]["params"].as_object().unwrap();
        let roles: std::collections::BTreeSet<_> = mappings.keys().map(String::as_str).collect();
        assert_eq!(
            roles,
            [
                "fx.delay",
                "fx.delay_feedback",
                "fx.delay_freeze",
                "fx.delay_spread",
                "fx.delay_time",
                "fx.delay_wobble",
                "fx.delay_wobble_rate",
            ]
            .into_iter()
            .collect()
        );
        for (role, id) in mappings {
            let id = id.as_str().unwrap();
            assert!(live.contains(id), "{role} points at missing `{id}`");
        }
    }

    #[test]
    fn every_shipped_recipe_is_what_the_generator_emits_today() {
        // Counts, uniqueness and completeness all pass on stale files, so nothing else in this
        // suite notices a design edited without rerunning the generator. Compare the committed
        // bytes against a fresh in-memory generation instead.
        let generated = crate::preset_designs::generate();
        assert_eq!(
            generated.len(),
            FACTORY_FILES.len(),
            "the bank and the source table disagree on how many sounds ship"
        );
        let shipped: std::collections::HashMap<_, _> = FACTORY_FILES.iter().copied().collect();
        for (slug, json) in &generated {
            let committed = shipped.get(slug.as_str()).unwrap_or_else(|| {
                panic!("{slug} is in the source table but no such file is compiled in")
            });
            if cfg!(target_os = "windows") {
                assert_eq!(
                    committed.replace("\r\n", "\n"),
                    *json,
                    "{slug}.json is stale: rerun `cargo run -p mxm-fx-delay --release \
                     --example fx_delay_build_presets`"
                );
            } else {
                let parse = |text: &str| mxm_preset::Preset::parse(text, crate::CLAP_ID).unwrap();
                assert_same_within_rounding(&parse(committed), &parse(json), slug);
            }
        }
    }

    /// A shipped file against a fresh generation with each value compared within rounding,
    /// everything else exactly. The files hold Windows' bits, and each platform's maths library
    /// rounds in its own way: macOS computes some normalised values one step away (the owner,
    /// 2026-10-06: pin on Windows only).
    fn assert_same_within_rounding(
        shipped: &mxm_preset::Preset,
        generated: &mxm_preset::Preset,
        slug: &str,
    ) {
        for (id, value) in &shipped.params {
            let fresh = generated
                .params
                .get(id)
                .unwrap_or_else(|| panic!("{slug}.json is stale: {id} is no longer generated"));
            assert!(
                (value.v - fresh.v).abs() <= 1.0e-6,
                "{slug}.json is stale: {id} is {} in the file and {} when generated",
                value.v,
                fresh.v
            );
        }
        let (mut shipped, mut generated) = (shipped.clone(), generated.clone());
        for value in shipped
            .params
            .values_mut()
            .chain(generated.params.values_mut())
        {
            value.v = 0.0;
        }
        assert_eq!(shipped, generated, "{slug}.json is stale");
    }

    #[test]
    fn factory_bank_has_fifty_distinct_complete_mix_preserving_sounds() {
        use std::collections::BTreeSet;

        assert_eq!(crate::preset_designs::DESIGNS.len(), 50);
        assert_eq!(FACTORY_FILES.len(), 50);
        let mut names = BTreeSet::new();
        let mut fingerprints = BTreeSet::new();
        for (slug, json) in FACTORY_FILES {
            let preset = Preset::parse(json, crate::CLAP_ID).unwrap();
            assert!(
                names.insert(preset.name.clone()),
                "duplicate name {}",
                preset.name
            );
            assert!(!slug.is_empty());
            assert_eq!(preset.params.len(), 17, "{}", preset.name);
            assert!(!preset.params.contains_key("mix"), "{}", preset.name);
            assert_eq!(preset.params["freeze"].v, 0.0, "{}", preset.name);
            let fingerprint: Vec<_> = preset
                .params
                .iter()
                .map(|(id, value)| (id.clone(), value.v.to_bits()))
                .collect();
            assert!(
                fingerprints.insert(fingerprint),
                "duplicate sound {}",
                preset.name
            );
        }
    }
}
